---

- hosts: all
  become: true 
  pre_tasks:
 
  - name: update cache 
    apt:
      update_cache: yes 

- hosts: web_server
  become: true
  tasks:
  - name: intall nginx web server
    package:
      name:
        - nginx
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

- hosts: db_server
  become: true
  tasks:
  - name: installa maria db server
    apt:
     name: mariadb-server
    when: ansible_distribution == "Ubuntu" 
